option(
    'chassis-system-reset',
    type: 'feature',
    value: 'disabled',
    description: 'Enable chassis system power reset to allow removing power and restoring back',
)
option(
    'use-plt-rst',
    type: 'feature',
    value: 'disabled',
    description: 'Use the PLT_RST eSPI signal to detect warm reset instead of POST Complete',
)
option(
    'use-acboot',
    type: 'feature',
    value: 'disabled',
    description: 'Use hardware Reset Reason to control Power Restore. Note: this only works with Intel-BMC',
)
option(
    'ignore-soft-resets-during-post',
    type: 'feature',
    value: 'disabled',
    description: 'Ignore soft resets from host during POST',
)
option(
    'button-passthrough',
    type: 'feature',
    value: 'disabled',
    description: 'Directly couple through power and reset buttons',
)

option(
    'gb300-pdb-iox-path',
    type: 'string',
    value: '/sys/bus/i2c/drivers/pca953x/9-0075',
    description: 'GB300 PDB IOX PCA953x driver bound path',
)
option(
    'c2-pdb-iox-path',
    type: 'string',
    value: '/sys/bus/i2c/drivers/pca953x/9-0024',
    description: 'C2 PDB IOX PCA953x driver bound path',
)
option(
    'nvl144-pdb-iox-path',
    type: 'string',
    value: '/sys/bus/i2c/drivers/pca953x/9-0020',
    description: 'NVL144 PDB IOX PCA953x driver bound path',
)
option(
    'board0-iox-path',
    type: 'string',
    value: '/sys/bus/i2c/drivers/pca953x/2-0020',
    description: 'Board 0 IOX PCA953x driver bound path',
)
option(
    'board1-iox-path',
    type: 'string',
    value: '/sys/bus/i2c/drivers/pca953x/7-0020',
    description: 'Board 1 IOX PCA953x driver bound path',
)
option(
    'obmc-standby-target',
    type: 'string',
    value: 'multi-user.target',
    description: 'The default obmc standby target.',
)
option(
    'enable-bmc-poweroff',
    type: 'feature',
    value: 'disabled',
    description: 'Enable BMC PowerOff transition (requires custom phosphor-dbus-interfaces with PowerOff enum)',
)
option(
    'install-powerctrl',
    type: 'feature',
    value: 'disabled',
    description: 'Install the D-Bus based powerctrl.sh script from this repo',
)
option(
    'cpu-reset-early-assert-war',
    type: 'feature',
    value: 'disabled',
    description: 'Enable workaround for hardware bug where CPU_RESET asserts before entering waitForCPUResetAssert state (old/broken hardware only)',
)
