@startuml

state "Host Graceful Shutdown" as HostPowerOff

note bottom of HostPowerOff
|= Source State |= Event |= Target State |= Handler |= Action Function |= Description |
| Host Power On | gracefulPowerOffRequest | Host Graceful Transition To Off | gracefulTransitionToOff | gracefulPowerOffTimerStart() & gracefulPowerOff(); | Host Graceful Shutdown Sequence Started:\n 1. Graceful power-off timer started \n 2. Assert SHDN_REQ_L-O for ShdnReqPulseMs defined duration |
| Host Graceful Transition To Off | psPowerOKDeAssert | Host Power Off | powerStateGracefulTransitionToOff | TBD() | RUN_POWER_PG-I de-asserted so Graceful Shutdown sequence completed successfully: \n 1. Cancel Graceful power-off timer \n 2. Stop SHDN_REQ_L-O assertion |
| Host Graceful Transition To Off | powerOffRequest | Host Power On | powerStateGracefulTransitionToOff | TBD() | Graceful shutdown failed because of RUN_POWER_PG-I de-assertion timeout:\n 1. Stop SHDN_REQ_L-O assertion|
| Host Graceful Transition To Off | gracefulPowerOffTimerExpired | Host Wait For Shutdown Ok | powerStateGracefulTransitionToOff | forcePowerOff() | Received a Forceful Shutdown Request during Graceful Shutdown: \n 1. Stop SHDN_REQ_L-O assertion \n 2. Cancel Graceful power-off timer \n 3. Assert SHDN_FORCE_L-O to 0 \n 4. Start watchdog timer for SHDN_OK_L-I assertion |
| Host Wait For Shutdown Ok | shutdownOKAssert | Host Transition To Power Off | powerStateWaitForShutdown | TBD() | SHDN_OK_L-I asserted successfully:\n 1. Cancel watchdog timer for SHDN_OK_L-I assertion \n 2. De-assert RUN_POWER_EN-O \n 3. Start watchdog for RUN_POWER_PG-I to de-assert |
| Host Wait For Shutdown Ok | shutdownOKWatchdogTimerExpired | Host Power On | powerStateWaitForShutdown | TBD() | Forceful shutdown failed because of SHDN_OK_L-I assertion timeout:\n 1. De-assert SHDN_FORCE_L-O (cleanup) |
| Host Wait For Shutdown Ok | psPowerOKDeAssert | Host Power Off | powerStateWaitForShutdown | TBD() | Unexpected power loss during Forceful Shutdown Sequence:\n 1. De-assert SHDN_FORCE_L-O \n 2. De-assert RUN_POWER_EN-O to match RUN_POWER_PG-I |
| Host Transition To Power Off | psPowerOKDeAssert | Host Power Off | powerStateTransitionPowerOff | TBD() | RUN_POWER_PG-I de-asserted so Forceful Shutdown sequence completed successfully: \n 1. Cancel watchdog for RUN_POWER_PG-I to de-assert \n 2. De-assert SHDN_FORCE_L-O (cleanup) |
| Host Transition To Power Off | psPowerOKWatchdogTimerExpired | Host Power On | powerStateTransitionPowerOff | TBD() | Forceful shutdown failed because of RUN_POWER_PG-I de-assertion timeout: \n 1. De-assert SHDN_FORCE_L-O (cleanup) \n 2. Assert RUN_POWER_EN-O to match RUN_POWER_PG-I |
end note

@enduml
