@startuml
scale 600 width

state "Host Power On\n<<powerStateOn>>" as HostPowerOn
state "Host Waiting For Power Rail to Power On <<powerStateWaitForPSPowerOK>>" as WaitForPSPowerOK
state "Host Waiting For System Reset Release <<powerStateWaitForSystemResetRelease>>" as WaitForSystemRstRelease
state "Host Power Off\n<<powerStateOff>>" as HostPowerOff
state fork_state <<fork>>

' Unique to Forceful Shutdown States:
state "Host Wait For Shutdown Ok\n<<powerStateWaitForShutdown>>" as Wait4ShutdownOk
state "Host Transition To Power Off\n<<powerStateTransitionPowerOff>>" as HostTransitionToOff

[*] --> HostPowerOff

HostPowerOff --> HostPowerOn : Event::psPowerOKAssert

HostPowerOff --> WaitForPSPowerOK : Event::powerOnRequest
HostPowerOff --> fork_state : Event::powerOnRequest 


fork_state --> WaitForPSPowerOK : RUN_POWER_PG-I == 0
fork_state --> HostPowerOn : RUN_POWER_PG-I = 1


WaitForPSPowerOK --> WaitForSystemRstRelease : Event::psPowerOKAssert
WaitForPSPowerOK --> HostPowerOff : Event::psPowerOKWatchdogTimerExpired

WaitForSystemRstRelease --> HostPowerOn : Event::systemResetReleaseAssert
WaitForSystemRstRelease --> Wait4ShutdownOk : Event::systemResetReleaseWatchdogTimerExpired

' Entered Forceful Shutdown Flow:
Wait4ShutdownOk --> HostTransitionToOff : Event::shutdownOKAssert
Wait4ShutdownOk --> HostPowerOn : Event::shutdownOKWatchdogTimerExpired
Wait4ShutdownOk --> HostPowerOff : Event::psPowerOKDeAssert

HostTransitionToOff --> HostPowerOff : Event::psPowerOKDeAssert
HostTransitionToOff --> HostPowerOn : Event::psPowerOKWatchdogTimerExpired



' === Mapping Table ===
note bottom of HostPowerOn
|= Source State |= Event |= Target State |= Handler |= Action Function |= Description |
| Host Power Off | psPowerOKAssert | Host Power On | powerStateOff | TBD() | Unexpected Power Gain :\n 1. Assert RUN_POWER_EN-O to match RUN_POWER_PG-I |
| Host Power Off | powerOnRequest | Host Waiting For Power Rail to Power On | powerStateOff | powerOn() | Host Main Power On Sequence Started:\n 1. Start Power Supply Power Ok Watchdog timer.\n 2. De-assert SHDN_REQ_L-O\n 3. De-assert SHDN_FORCE_L-O\n 4. Assert SYS_RST_IN_L-O (hold host in reset)\n 5. Set RUN_POWER_EN-O high permanently (enable power to FPGA) |
| Host Power Off | powerOnRequest | Host Power On | powerStateOff | powerOn() | RUN_POWER_PG-I already asserted so Main Power Rail is already Powered On: 1. Assert RUN_POWER_EN-O to match RUN_POWER_PG-I |
| Host Waiting For Power Rail to Power On | psPowerOKAssert | Host Waiting For System Reset Release | powerStateWaitForPSPowerOK | TBD() | RUN_POWER_PG-I asserted. Succesful FPGA Power On completed. Wait For System Reset Release: 1. Cancel any gpio assertions\n 2. Cancel Power Supply Power Ok Watchdog timer\n 3. De-assert SYS_RST_IN_L-O (clean up)\n 4. Start System Reset Release Watchdog timer |
| Host Waiting For Power Rail to Power On | psPowerOKWatchdogTimerExpired | Host Power Off | powerStateWaitForPSPowerOK | TBD() | Host Main Power On failed because of RUN_POWER_PG-I assertion timeout:\n 1. Cancel any gpio assertions\n 2. De-assert RUN_POWER_EN-O\n 3. De-assert SYS_RST_IN_L-O\n 4. Formally log Power On Failure |
| Host Waiting For System Reset Release | systemResetReleaseAssert | Host Power On | powerStateWaitForSystemResetRelease | TBD() | System Reset Release Asserted. Host Power On Successful: 1. Cancel any gpio assertions\n 2. Cancel System Reset Release Watchdog timer |
| Host Waiting For System Reset Release | systemResetReleaseAssert | Host Wait For Shutdown Ok | powerStateWaitForSystemResetRelease | TBD() | System Reset Release failed because of SYS_RST_OUT_L-I assertion timeout. Host Power On failed. Conducting Host Forceful Shutdown:\n 1. Assert SHDN_FORCE_L-O to 0 \n 2. Start watchdog timer for SHDN_OK_L-I assertion |
| Host Wait For Shutdown Ok | shutdownOKAssert | Host Transition To Power Off | powerStateWaitForShutdown | TBD() | SHDN_OK_L-I asserted successfully:\n 1. Cancel watchdog timer for SHDN_OK_L-I assertion \n 2. De-assert RUN_POWER_EN-O \n 3. Start watchdog for RUN_POWER_PG-I to de-assert |
| Host Wait For Shutdown Ok | shutdownOKWatchdogTimerExpired | Host Power On | powerStateWaitForShutdown | TBD() | Forceful shutdown failed because of SHDN_OK_L-I assertion timeout:\n 1. De-assert SHDN_FORCE_L-O (cleanup) |
| Host Wait For Shutdown Ok | psPowerOKDeAssert | Host Power Off | powerStateWaitForShutdown | TBD() | Unexpected power loss during Forceful Shutdown Sequence:\n 1. De-assert SHDN_FORCE_L-O \n 2. De-assert RUN_POWER_EN-O to match RUN_POWER_PG-I |
| Host Transition To Power Off | psPowerOKDeAssert | Host Power Off | powerStateTransitionPowerOff | TBD() | RUN_POWER_PG-I de-asserted so Forceful Shutdown sequence completed successfully: \n 1. Cancel watchdog for RUN_POWER_PG-I to de-assert \n 2. De-assert SHDN_FORCE_L-O (cleanup) |
| Host Transition To Power Off | psPowerOKWatchdogTimerExpired | Host Power On | powerStateTransitionPowerOff | TBD() | Forceful shutdown failed because of RUN_POWER_PG-I de-assertion timeout: \n 1. De-assert SHDN_FORCE_L-O (cleanup) \n 2. Assert RUN_POWER_EN-O to match RUN_POWER_PG-I |
end note


@enduml