@startuml
scale 800 width
top to bottom direction
skinparam state {
  Padding 8
  Shadowing false
}
skinparam nodesep 50
skinparam ranksep 60

' --- Global States ---
state "Host Power Off\n<<powerStateOff>>" as HostPowerOff
state "Host Power On\n<<powerStateOn>>" as HostPowerOn

' --- Power Cycle FSM States ---
state "Host Wait For Shutdown Ok\n<<powerStateWaitForShutdownOKToCycleOff>>" as Wait4ShutdownOkToCycleOff
state "Host Transition To Cycle Power Off\n<<powerStateTransitionToCycleOff>>" as HostTransitionToCycleOff
state "Host Cycle Power Off\n<<powerStateCycleOff>>" as HostCycleOff

' --- Initial State ---
[*] -[#green]-> HostPowerOn

' --- Power Cycle FSM Transitions ---
HostPowerOn -[#green]-> Wait4ShutdownOkToCycleOff : <color:green>Event::powerCycleRequest</color>

Wait4ShutdownOkToCycleOff -[#green]-> HostTransitionToCycleOff : <color:green>Event::shutdownOKAssert</color>
Wait4ShutdownOkToCycleOff --> HostPowerOn : Event::shutdownOKWatchdogTimerExpired
Wait4ShutdownOkToCycleOff --> HostCycleOff : Event::psPowerOKDeAssert

HostTransitionToCycleOff -[#green]-> HostCycleOff : <color:green>Event::psPowerOKDeAssert</color>
HostTransitionToCycleOff --> HostPowerOn : Event::psPowerOKWatchdogTimerExpired

HostCycleOff --> HostPowerOn : Event::psPowerOKAssert
HostCycleOff -[#green]-> HostMainPowerOn.fork_state : <color:green>Event::powerCycleTimerExpired</color>

' --- Host Main Power On Composite ONLY contains these states ---
state "Host Main Power On" as HostMainPowerOn {
    state fork_state <<fork>>
    state "Host Waiting For Power Rail to Power On\n<<powerStateWaitForPSPowerOK>>" as WaitForPSPowerOK
    state "Host Waiting For System Reset Release\n<<powerStateWaitForSystemResetRelease>>" as WaitForSystemRstRelease

    fork_state -[#green]-> WaitForPSPowerOK : <color:green>RUN_POWER_PG-I == 0</color>
    fork_state --> HostPowerOn : RUN_POWER_PG-I == 1

    WaitForPSPowerOK -[#green]-> WaitForSystemRstRelease : <color:green>Event::psPowerOKAssert</color>
    WaitForPSPowerOK --> HostPowerOff : Event::psPowerOKWatchdogTimerExpired

    WaitForSystemRstRelease -[#green]-> HostPowerOn : <color:green>Event::systemResetReleaseAssert</color>
    WaitForSystemRstRelease --> ForcefulShutdown.Wait4ShutdownO : Event::systemResetReleaseWatchdogTimerExpired
}

' --- Forceful Shutdown Composite SEPARATE ---
state "Host Forceful Shutdown" as ForcefulShutdown {
    state "Host Wait For Shutdown Ok\n<<powerStateWaitForShutdown>>" as Wait4ShutdownOk
    state "Host Transition To Power Off\n<<powerStateTransitionPowerOff>>" as HostTransitionToOff

    Wait4ShutdownOk --> HostTransitionToOff : Event::shutdownOKAssert
    Wait4ShutdownOk --> HostPowerOn : Event::shutdownOKWatchdogTimerExpired
    Wait4ShutdownOk --> HostPowerOff : Event::psPowerOKDeAssert

    HostTransitionToOff --> HostPowerOff : Event::psPowerOKDeAssert
    HostTransitionToOff --> HostPowerOn : Event::psPowerOKWatchdogTimerExpired
}

@enduml

