@startuml
scale 600 width

state "Host Power On\n<<powerStateOn>>" as HostPowerOn
state "Host Wait For Shutdown Ok\n<<powerStateWaitForShutdown>>" as Wait4ShutdownOk
state "Host Transition To Power Off\n<<powerStateTransitionPowerOff>>" as HostTransitionToOff
state "Host Power Off\n<<powerStateOff>>" as HostPowerOff

[*] -[#green]-> HostPowerOn

HostPowerOn -[#green]-> Wait4ShutdownOk : <color:green>Event::powerOffRequest</color>

Wait4ShutdownOk -[#green]-> HostTransitionToOff : <color:green>Event::shutdownOKAssert</color>
Wait4ShutdownOk --> HostPowerOn : Event::shutdownOKWatchdogTimerExpired
Wait4ShutdownOk --> HostPowerOff : Event::psPowerOKDeAssert

HostTransitionToOff -[#green]-> HostPowerOff : <color:green>Event::psPowerOKDeAssert</color>
HostTransitionToOff --> HostPowerOn : Event::psPowerOKWatchdogTimerExpired

@enduml