@startuml
!pragma layout vertical  /* attempt a vertical-first layout */

start

:HostPowerOff;

-->[Event::powerOnRequest];

split
  :RUN_POWER_PG-I == 0;
  :WaitForPSPowerOK;
split again
  :RUN_POWER_PG-I == 1;
  :HostPowerOn;
end split


' if (HostPowerOff) then (Event::powerOnRequest)
'   -> WaitForPSPowerOK
' endif

' if (powerOnRequest?) then (yes)
'   :powerOn() action;\nDe-assert SHDN_REQ, SHDN_FORCE, assert SYS_RST_IN, enable RUN_POWER_EN;
'   -> WaitForPSPowerOK
' else (no)
'   stop
' endif

' :WaitForPSPowerOK;

' if (psPowerOKAssert?) then (yes)
'   -> WaitForSystemResetRelease
' else if (psPowerOKTimeout?) then (timeout)
'   :Cancel GPIOs;\nDe-assert RUN_POWER_EN & SYS_RST_IN;\nLog failure;
'   -> HostPowerOff
' endif

' :WaitForSystemResetRelease;

' if (systemResetReleaseAssert?) then (yes)
'   :Cancel timers, de-assert SYS_RST_IN;\nSuccess;
'   -> HostPowerOn
' else if (systemResetTimeout?) then (timeout)
'   :Assert SHDN_FORCE = 0;\nStart SHDN_OK timer;
'   -> WaitForShutdownOk
' endif

' :WaitForShutdownOk;

' if (shutdownOKAssert?) then (yes)
'   :Cancel SHDN_OK timer;\nDe-assert RUN_POWER_EN;\nStart PG de-assert watch;
'   -> HostTransitionToOff
' else if (shutdownTimeout?) then (timeout)
'   :De-assert SHDN_FORCE;\n(cleanup failure)
'   -> HostPowerOn  /* or maybe retry or fail path */
' else if (psPowerOKDeAssert?) then (power lost)
'   :De-assert SHDN_FORCE & RUN_POWER_EN;\nUnexpected loss;
'   -> HostPowerOff
' endif

' :HostTransitionToOff;

' if (psPowerOKDeAssert?) then (yes)
'   :Cancel PG de-assert timer;\nDe-assert SHDN_FORCE;\nDone;
'   -> HostPowerOff
' else if (pgDeassertTimeout?) then (timeout)
'   :Cleanup and assert RUN_POWER_EN back;\nRetry or failure;
'   -> HostPowerOn
' endif

@enduml
